//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Management_System.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication_History
    {
        public int CommunicationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
        public string CommunicationType { get; set; }
        public int ContactID { get; set; }
    }
}
