//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Management_System.DAL.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ACMEDb : DbContext
    {
        public ACMEDb()
            : base("name=ACMEDb")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Communication_History> Communication_History { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
    }
}
